apiVersion: apps/v1
kind: Deployment
metadata:
  name: allergy-service
spec:
  selector:
    matchLabels:
      run: allergy-service-label
  replicas: 2
  template:
    metadata:
      labels:
        run: allergy-service-label
    spec:
      containers:
        - name: allergy-service-container
          image: azkesakkip/allergy-svc
          ports:
            - containerPort: 8082
              hostPort: 8082


